[features]
seeds = false
[programs.localnet]
solana_twitter = "6Yg11PwCxVuvGXxqMC3uTRb5T6XqkXw1eJVNfT24zxsw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tests/tsconfig.tests.json -t 1000000 tests/anchor.ts"
