[features]
seeds = false
[programs.devnet]
emoji_exchange = "7chu7NvG5P8fAKYv6tGUnGEPb6WV28kGK9xiWExfwNSG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cp ./target/idl/emoji_exchange.json ./app/src/utils/idl.json && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/emoji-exchange.ts"
